# hw/arm/meson.build entries for i.MX RT1180

# To be merged into upstream QEMU hw/arm/meson.build:
# Add the following lines:
#
# imxrt1180_ss = ss.source_set()
# imxrt1180_ss.add(when: 'CONFIG_IMXRT1180_SOC', if_true: files(
#   'imxrt1180_soc.c',
#   'imxrt1180_evk.c',
# ))
# system_ss.add_all(when: 'CONFIG_IMXRT1180_SOC', if_true: imxrt1180_ss)

# Also add to Kconfig:
# config IMXRT1180_SOC
#     bool
#     select ARM_V7M
#     select IMXRT1180_ENET
